build:
  - ".github/**/*"
  - ".gitignore"
  - "phpcs.xml.dist"

dependencies:
  - "composer.json"
  - "composer.lock"

enhancement:
  - "src/**/*"

tests:
  - 'tests/**/*'
  - 'phpunit.xml.dist'
  - 'tests.sh'

documentation:
  - "readme.md"
  - "LICENSE"
  - "flow.png"
