template: |
  ## Changes
  $CHANGES
change-template: '- **$TITLE** (#$NUMBER)'

version-template: "$MAJOR.$MINOR.$PATCH"
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'dependencies'
  - title: 'Maintenance'
    labels:
      - 'build'
      - 'refactoring'
      - 'documentation'
      - 'tests'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'refactoring'
  minor:
    labels:
      - 'feature'
      - 'minor'
      - 'enhancement'
      - 'dependencies'
  patch:
    labels:
      - 'patch'
      - 'build'
      - 'bug'
      - 'bugfix'
      - 'hotfix'
      - 'fix'
      - 'documentation'
      - 'tests'
  default: 'patch'
