template: |
  ## Changes
  $CHANGES
change-template: '- **$TITLE** (#$NUMBER)'

version-template: "$MAJOR.$MINOR.$PATCH"
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'type:common'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'dependencies'
  - title: 'Maintenance'
    labels:
      - 'type:build'
      - 'refactoring'
      - 'theme:docs'
      - 'type:tests'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'refactoring'
  minor:
    labels:
      - 'feature'
      - 'minor'
      - 'type:common'
  patch:
    labels:
      - 'patch'
      - 'type:build'
      - 'bug'
      - 'bugfix'
      - 'hotfix'
      - 'fix'
      - 'theme:docs'
      - 'type:tests'
  default: 'patch'
